$schema: "http://json-schema.org/draft-07/schema#"
$id: "http://example.com/product.schema.json"
title: "Settings"
description: "Tbot user settings file"
type: "object"
properties:
  exchanges:
    description: "The exchanges defined by the user"
    type: "array"
    properties:
      name:
        type: "string"
      type:
        type: "string"
      apiKey:
        type: "string"
      apiSecret:
        type: "string"
    required: ["name", "type"]
  strategies:
    description: "The strategies defined by the user"
    type: "array"
    properties:
      name:
        type: "string"
      type:
        type: "string"
      risk:
        type: "integer"
      exchange:
        type: "string"
    required: ["name", "type", "risk", "exchange"]


